#!/usr/bin/env bash
# install nginx
# nginx should listen at port 80

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx start
