#!/usr/bin/env bash
# script that configures a new ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'NGINX HTTP'
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^ /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
