#!/usr/bin/env bash
# configuring HAProxy load balancer

# update the package list
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# add the HAProxy repositiory and install HAProxy 2.0
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
	bind *.80
	mode http
	default_backend webservers

backend webservers
	balance roundrobin
	server 396563-web-01 54.164.121.37:80 check
	server 396563-web-02 35.174.185.44:80 check
"
# add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" | sudo tee /etc/haproxy/haproxy/haproxy.cfg

# start the HAProxy service
sudo service haproxy start
