#!/usr/bin/env bash
# this script prints best school using while and if loops
n=1
while [ $n -lt 11 ]; do
	if [ $n -eq 4 ]; then
		echo "bad luck"
	elif [ $n -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
